import Head from 'next/head';
import Ads from '../components/Ads';
import Categories from '../components/Categories';
import Featured from '../components/Featured';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import Service from '../components/Service';
import SpecialProducts from '../components/SpecialProducts';

export default function Home() {
  return (
    <div className="container mx-auto max-w-7xl">
      <Head>
        <title>Alstore - Find everything you want</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-8" />
      <Hero />
      <div className="py-8" />
      <Service />
      <div className="py-8" />
      <Categories />
      <div className="py-8" />
      <Featured />
      <div className="py-8" />
      <Ads />
      <div className="py-8" />
      <SpecialProducts />
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
